version: '3'

services:
  app:
    container_name: confianza-publica-app
    build: .
    command: ["./node_modules/.bin/gulp", "bws"]
    environment:
      - NODE_ENV=development
      - DEBUG=democracyos*
      - MONGO_URL=mongodb://localhost:27017/lala
      - JWT_SECRET=6BB8C00A05ECEA4C04E81BEFB13B9FBBC3175E47839644CCC1CCA1D4641FB980FBBC3175E47839644CCC1CCA1D4641FB980
      - NOTIFICATIONS_NODEMAILER={"host":"smtp.mailtrap.io","port":2525,"auth":{"user":"a25e4cb76d8eb0","pass":"f304115d9cf487"},"maxConnections":1,"rateLimit":"true","pool":"true","maxMessages":1}
      - PORT=3000
      - STAFF=guillermocroppi@gmail.com
      - NOTIFICATIONS_MAILER_EMAIL=guillermocroppi@gmail.com

      # - CUSTOM_SIGNIN=true/false
      # - OIDC_ISSUER=**************
      # - OIDC_AUTH=**************
      # - OIDC_TOKEN=**************
      # - OIDC_USER=**************
      # - OIDC_CLIENT_ID=**************
      # - OIDC_CLIENT_SECRET=**************
      # - OIDC_CALLBACK=**************
    # links:
    #   - mongo
    ports:
      - 3000:3000
    volumes:
      - ./ext/lib:/usr/src/ext/lib
      - ./public:/usr/src/public
      # Add every forced override to democracyos
      - ./dos-override/models/comment.js:/usr/src/lib/models/comment.js
      - ./dos-override/api-v2/db-api/comments/index.js:/usr/src/lib/api-v2/db-api/comments/index.js
      - ./dos-override/api-v2/db-api/comments/scopes.js:/usr/src/lib/api-v2/db-api/comments/scopes.js
    tty: true
    network_mode: "host"


  # mongo:
  #   container_name: sunchales-mongo
  #   image: mongo:3.2
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./tmp/db:/data/db